apiVersion: v1
kind: Service
metadata:
  name: external-db-service
spec:
  type: ExternalName # Type is used to expose the service outside the cluster
  externalName: remote.db.example.com # ExternalName is used to expose the service outside the cluster