apiVersion: v1
kind: Service
metadata:
  name: external-database-service
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
 

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-database-endpoints
  labels:
    kubernetes.io/service-name: external-database-service
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.100
      - 192.168.1.101
ports:
  - name: mysql
    protocol: TCP
  - port: 3306